
AR=ar crs
RAN=ranlib
CC=gcc 
LD=gcc 
RM=rm -f
INSTALL=install
srcdir = src
libdir = lib

INCLUDE = -I. -I.. -I../$(srcdir) -I../$(libdir)
CFLAGS=-Wall -O2 
LFLAGS= -L../lib -labplc5
LIBSUBDIRS = lib
UTILSUBDIRS = src

all utils:  

clean:
	$(RM) *~ 

dist:
	

